kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: k8s-api-nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: k8s-api-nginx
    spec:
      containers:
      - name: k8s-api-nginx
        image: "lsstsqre/k8s-api-nginx"
        imagePullPolicy: "Always"
        env:
          - name: ENABLE_SSL
            value: 'true'
          - name: ENABLE_BASIC_AUTH
            value: 'false'
          - name: HOSTNAME
            valueFrom:
              secretKeyRef:
                name: k8s-api-nginx
                key: hostname
        ports:
          - name: http
            containerPort: 80
          - name: https
            containerPort: 443
        volumeMounts:
        - name: tls
          mountPath: /etc/tls
          readOnly: true
      volumes:
      - name: tls
        secret:
          secretName: ssl-proxy-secret
      
